stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/data.csv
    - src/preprocess.py
    params:
    - preprocess.input
    - preprocess.output
    outs:
    - data/processed/preprocessed_data.csv
  train:
    cmd: python src/train.py
    deps:
    - data/raw/data.csv
    - src/train.py
    params:
    - train.input
    - train.max_depth
    - train.output
    - train.n_estimators
    - train.random_state
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/eval.py
    deps:
    - data/raw/data.csv
    - models/model.pkl
    - src/eval.py
