preprocess:
  input: data/raw/data.csv
  output: data/processed/preprocessed_data.csv

train:
  input: data/processed/preprocessed_data.csv
  output: models/model.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 5